# Copyright IBM Corp. 2024, 2025
# SPDX-License-Identifier: MPL-2.0

contact_links:
  - name: Ask a question
    url: https://discuss.hashicorp.com/c/boundary
    about: For increased visibility, please post questions on the discussion forum.
